#ifndef ESP_INT8_APP_CONFIG_H
#define ESP_INT8_APP_CONFIG_H

#include "xil_types.h"

#define INT8_APP_BUILD_TAG "INT8-BOARD-20260923-P7-H256W512-R4R-DUAL-PROF"
/* Fallback profile for the single-model/prefix modes; dual mode uses both below. */
#define INT8_APP_DEPLOYMENT_NAME "cityscapes20"
#define INT8_APP_EXPECTED_CLASS_COUNT 20U

#define INT8_APP_PL_TARGET_HZ 100000000ULL
#define INT8_APP_PL_TARGET_PERIOD_NS 10U
#define INT8_APP_TIMER_SELFTEST_US 100000U
#define INT8_APP_TIMER_SELFTEST_MAX_ERR_PPM 50000U

#define INT8_PARAM_FILE "P20H.BIN"
#define INT8_INPUT_FILE "I20H.BIN"
#define INT8_OUTPUT_FILE "O20H.BIN"

#define INT8_APP_INPUT_H 256U
#define INT8_APP_INPUT_W 512U
#define INT8_APP_INPUT_C 3U
#define INT8_APP_OUTPUT_H 256U
#define INT8_APP_OUTPUT_W 512U
#define INT8_INPUT_BYTES (INT8_APP_INPUT_H * INT8_APP_INPUT_W * INT8_APP_INPUT_C)
#define INT8_OUTPUT_BYTES (INT8_APP_OUTPUT_H * INT8_APP_OUTPUT_W)

#define INT8_PARAM_HW_WORD_BYTES 32U
#define INT8_PARAM_HW_WORDS 8192U
#define INT8_PARAM_HW_MAX_BYTES (INT8_PARAM_HW_WORD_BYTES * INT8_PARAM_HW_WORDS)

#define INT8_PARAM_BLOB_MAGIC 0x544E4945U
#define INT8_PARAM_BLOB_VERSION_CURRENT 4U
#define INT8_EXPECTED_UOP_COUNT 75U
#define INT8_EXPECTED_EXEC_PLAN_COUNT 16U
#define INT8_MAX_EXEC_PLAN_COUNT 96U
#define INT8_PARAM_HEADER_BYTES 128U
#define INT8_UOP_BYTES 32U
#define INT8_EXEC_PLAN_ENTRY_BYTES 4U
#define INT8_EXEC_KIND_END 255U

#define INT8_NPU_MODE_INIT 1U
#define INT8_NPU_MODE_RUN 2U

#define INT8_NPU_TIMEOUT_POLLS 600000000U
#define INT8_NPU_LIVE_DEBUG_INTERVAL_POLLS 0U

#define INT8_APP_QUIET_PERF 1U

#define INT8_STAGE_COUNTER_STAGE_COUNT 13U
#define INT8_APP_REQUIRE_CONV_PROFILE 1U

#define INT8_APP_ENABLE_EXEC_PREFIX_PROFILE 0U
#define INT8_APP_EXEC_PREFIX_COUNT 16U
/* Prefix mode is disabled for the dual-model full-network profiling run. */
#define INT8_APP_EXEC_PREFIX_REFERENCE_FULL_RTL_CYCLES 0ULL
#define INT8_APP_EXEC_PREFIX_TARGET_MAX_RTL_CYCLES 0ULL

#define INT8_APP_ENABLE_VAL_SET_TEST 0U
#define INT8_APP_ENABLE_DUAL_VAL_SET_TEST 0U
#define INT8_APP_ENABLE_DUAL_SINGLE_TEST 1U
#define INT8_APP_DUAL_VAL_MAX_IMAGES 500U
#define INT8_APP_BINARY_PARAM_FILE "P2H.BIN"
#define INT8_APP_BINARY_SINGLE_INPUT_FILE "I2H.BIN"
#define INT8_APP_BINARY_SINGLE_OUTPUT_FILE "O2H.BIN"
#define INT8_APP_BINARY_INPUT_PREFIX "B/B"
#define INT8_APP_BINARY_OUTPUT_PREFIX "Q/Q"
#define INT8_APP_BINARY_CLASS_COUNT 2U
#define INT8_APP_CLASS20_PARAM_FILE "P20H.BIN"
#define INT8_APP_CLASS20_SINGLE_INPUT_FILE "I20H.BIN"
#define INT8_APP_CLASS20_SINGLE_OUTPUT_FILE "O20H.BIN"
#define INT8_APP_CLASS20_INPUT_PREFIX "C/C"
#define INT8_APP_CLASS20_OUTPUT_PREFIX "D/D"
#define INT8_APP_CLASS20_CLASS_COUNT 20U
#define INT8_APP_ENABLE_SINGLE_PERF_BEFORE_VAL 0U
#define INT8_APP_SINGLE_PERF_INPUT_FILE INT8_INPUT_FILE
#define INT8_APP_SINGLE_PERF_OUTPUT_FILE INT8_OUTPUT_FILE
#define INT8_APP_SINGLE_PERF_FALLBACK_INDEX 0U
#define INT8_APP_VAL_START_INDEX 0U
#define INT8_APP_VAL_MAX_IMAGES 500U
#define INT8_APP_VAL_PROGRESS_EVERY 50U
#define INT8_APP_VAL_INPUT_PREFIX "I"
#define INT8_APP_VAL_OUTPUT_PREFIX "O"

#endif
