#ifndef ESP_INT8_APP_CONFIG_H
#define ESP_INT8_APP_CONFIG_H

#include "xil_types.h"

#define INT8_APP_BUILD_TAG "INT8-BOARD-20260615-P6J-TC100-VAL"

#define INT8_APP_PL_TARGET_HZ 100000000ULL
#define INT8_APP_PL_TARGET_PERIOD_NS 10U
#define INT8_APP_TIMER_SELFTEST_US 100000U
#define INT8_APP_TIMER_SELFTEST_MAX_ERR_PPM 50000U

#define INT8_PARAM_FILE "PARAM.BIN"
#define INT8_INPUT_FILE "INPUTQ.BIN"
#define INT8_OUTPUT_FILE "MASK.BIN"

#define INT8_INPUT_BYTES (512U * 1024U * 3U)
#define INT8_OUTPUT_BYTES (512U * 1024U)

#define INT8_PARAM_HW_WORD_BYTES 32U
#define INT8_PARAM_HW_WORDS 4096U
#define INT8_PARAM_HW_MAX_BYTES (INT8_PARAM_HW_WORD_BYTES * INT8_PARAM_HW_WORDS)

#define INT8_PARAM_BLOB_MAGIC 0x544E4945U
#define INT8_PARAM_BLOB_VERSION 0x00010000U
#define INT8_EXPECTED_UOP_COUNT 75U
#define INT8_PARAM_HEADER_BYTES 128U
#define INT8_UOP_BYTES 32U

#define INT8_NPU_MODE_INIT 1U
#define INT8_NPU_MODE_RUN 2U

#define INT8_NPU_DEBUG_ENABLE_MASK 0x00000010U
#define INT8_NPU_DEBUG_SKIP_STORE_MASK 0x00000020U
#define INT8_NPU_DEBUG_DUMP_TENSOR_SHIFT 8U
#define INT8_NPU_DEBUG_DUMP_WORDS_SHIFT 16U
#define INT8_NPU_DEBUG_STOP_AFTER_SHIFT 16U
#define INT8_NPU_DEBUG_DUMP_WORDS 16384U
#define INT8_NPU_DEBUG_DUMP_TENSOR_DISABLED 0xffU

#define INT8_TID_INPUT 0U
#define INT8_TID_POOL1 1U
#define INT8_TID_B1_CAT 2U
#define INT8_TID_B1_ACT 3U
#define INT8_TID_L20_ACT 5U
#define INT8_TID_B2_ACT 10U
#define INT8_TID_L30_ACT 12U
#define INT8_TID_L3B0_ACT 14U
#define INT8_TID_OUT 17U

#define INT8_NPU_TIMEOUT_POLLS 600000000U
#define INT8_NPU_DEBUG_LONG_TIMEOUT_POLLS 4000000000U
#define INT8_NPU_LONG_DEBUG_START_UOP 2U
#define INT8_NPU_LIVE_DEBUG_INTERVAL_POLLS 0U

#define INT8_APP_ENABLE_DEBUG_BRINGUP 0U
#define INT8_APP_RUN_FULL_AFTER_DEBUG 0U
#define INT8_APP_ENABLE_PREFIX_PROFILING 0U
#define INT8_APP_PREFIX_PROFILE_MAX_UOP 74U
#define INT8_APP_QUIET_PERF 1U

#define INT8_APP_ENABLE_VAL_SET_TEST 1U
#define INT8_APP_ENABLE_SINGLE_PERF_BEFORE_VAL 0U
#define INT8_APP_SINGLE_PERF_INPUT_FILE INT8_INPUT_FILE
#define INT8_APP_SINGLE_PERF_OUTPUT_FILE INT8_OUTPUT_FILE
#define INT8_APP_SINGLE_PERF_FALLBACK_INDEX 0U
#define INT8_APP_VAL_START_INDEX 0U
#define INT8_APP_VAL_MAX_IMAGES 500U
#define INT8_APP_VAL_PROGRESS_EVERY 1U
#define INT8_APP_VAL_INPUT_PREFIX "I"
#define INT8_APP_VAL_OUTPUT_PREFIX "O"

#endif
